### PR TITLE
Crm

### PR DESCRIPTION
**Pull request by AJ1904**
http://localhost:3000/api/users
image

### CODE REVIEW

**Comment by vibalcam** [comment]
What is the command for testing?

**Review by vibalcam — CHANGES_REQUESTED** [review]
Testing command missing

**Comment by AJ1904** [comment]
Test : cucumber features/crmapi.feature

image
image
image

**Comment by AJ1904** [comment]
> Test : cucumber features/crmapi.feature

Test : cucumber features/crmapi.feature

**Review by vibalcam — CHANGES_REQUESTED** [review]
Check CRM email from professor.

**Comment by AJ1904** [comment]
Test : cucumber features/crmapi.feature
This is accepted implementation as informed by CRMNxt Team.

**Review by vibalcam — APPROVED** [review]
Looks good

**Pull request merged**
